'use strict';// 홈 title slide 구현
var showing_class='showing',fitstClass=document.querySelector('.home__slide__title:first-child');function titleSlideFn(){var a=document.querySelector('.showing');if(a){a.classList.remove(showing_class);var b=a.nextElementSibling;b?b.classList.add(showing_class):fitstClass.classList.add(showing_class)}else fitstClass.classList.add(showing_class)}setTimeout(titleSlideFn),setInterval(titleSlideFn,4500);// header
var navBar=document.querySelector('#navbar'),navbarHeight=navBar.getBoundingClientRect().height;document.addEventListener('scroll',function(){window.scrollY>navbarHeight?navBar.classList.add('navbar--dark'):navBar.classList.remove('navbar--dark')});//header link
var navbarMenu=document.querySelector('.navbar__menu');navbarMenu.addEventListener('click',function(a){var b=a.target,c=b.dataset.link;console.log(c);null==c||scrollIntoView(c)});function scrollIntoView(a){var b=document.querySelector(a);b.scrollIntoView({behavior:'smooth'})}//contact btn 
var contactBtn=document.querySelector('.home__contact');contactBtn.addEventListener('click',function(){scrollIntoView('#contact')}),contactBtn.addEventListener('keyup',function(a){9==a.keyCode&&(contactBtn.style.color='#c291ed',contactBtn.style.backgroundColor='#eeeeee')});//toggle button
var navbarToggleBtn=document.querySelector('.navbar__toggle-btn'),navbarContainer=document.querySelector('.navbar__menu_container');navbarToggleBtn.addEventListener('click',function(){navbarContainer.classList.toggle('open')});//scrolling opacity
var home=document.querySelector('.home__container'),homeHeight=home.getBoundingClientRect().height;document.addEventListener('scroll',function(){home.style.opacity=1-window.scrollY/homeHeight});//skils 필터링
var categories=document.querySelector('.skills__categories'),skillContainer=document.querySelector('.skills__container'),skillDivede=document.querySelector('.skill__divide'),skillTitle=document.querySelectorAll('.skill__title');categories.addEventListener('click',function(a){var b=a.target.dataset.filter;null==b||skillsFilter(a)}),categories.addEventListener('keypress',function(a){var b=a.target.dataset.filter;'Enter'===a.key&&(console.log(b),skillsFilter(a))});function skillsFilter(a){var b=a.target.dataset.filter,c=!0,d=!1,e=void 0;try{for(var f,g,h=skillTitle[Symbol.iterator]();!(c=(f=h.next()).done);c=!0)g=f.value,'*'===b||b===g.dataset.type?g.classList.remove('indivisual'):g.classList.add('indivisual')}catch(a){d=!0,e=a}finally{try{!c&&h.return&&h.return()}finally{if(d)throw e}}}// blog btn animaition
var studyBtn=document.querySelector('.study__blog__btn');studyBtn.addEventListener('mouseover',function(){studyBtn.innerHTML='Learn More \uD83D\uDE00\uD83D\uDC49'}),studyBtn.addEventListener('mouseout',function(){studyBtn.innerHTML='Learn More'}),studyBtn.addEventListener('keyup',function(a){9==a.keyCode&&(studyBtn.innerHTML='Learn More \uD83D\uDE00\uD83D\uDC49',studyBtn.style.backgroundColor='#ffef45',studyBtn.style.color='#4d4d4d')});//go-top
var goTop=document.querySelector('.go__top'),showingArrow='showing__arrow';function goTopArrow(){document.addEventListener('scroll',function(){window.scrollY>homeHeight/2?goTop.classList.add(showingArrow):goTop.classList.remove(showingArrow)})}goTopArrow();